#!/bin/sh
# Amalgamate the Ambiotica port into ONE #include-free .cpp for the Plinky web
# IDE. Order: LOOPER_I16 define -> arena allocator (+ calloc redirect) -> module
# headers -> full_chain -> module implementations -> panel. All #include lines
# are stripped (Plinky auto-injects the standard headers; #include is banned).
set -e
HN="$(cd "$(dirname "$0")" && pwd)"
DSP="$HN/../dsp"
HARN="$HN/../harness"

# Build stamp for the generated header: which commit + when it was generated, so
# a downloaded drop-in shows its provenance (CI fills these on every push).
# Falls back gracefully outside a git checkout.
STAMP_HASH="$(git -C "$HN" rev-parse --short HEAD 2>/dev/null || echo nogit)"
git -C "$HN" diff --quiet HEAD 2>/dev/null || STAMP_HASH="${STAMP_HASH}-dirty"
STAMP_TIME="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

OUT="$HN/plinky_ambiotica.cpp"

strip() { grep -vE '^[[:space:]]*#[[:space:]]*include' "$1"; }

MODULES="looper granular microloop harmony bloom drift lfo dattorro drums"

{
    # Panel library metadata. MUST be the first BLOCK comment in the file — that is what
    # the panel library parses (plinkysynth/community-panels). Line comments below it are
    # fine. @Author and @Documentation are the required fields; @Artwork is banned for
    # community submissions (ship artwork.png beside the .cpp instead).
    cat <<'META'
/*
@Name: Ambiotica
@Author: Charles Vestal
@Documentation: https://github.com/charlesvestal/plinky-ambiotica
@Category: Instruments
@Tags: ambient, granular, reverb, looper, drone
@Discussion: https://github.com/charlesvestal/plinky-ambiotica/issues
@Description: Play a few notes and let go — a rolling looper, granular cloud and plate reverb bloom them into a slow, always-in-key ambient wash.

Ambiotica turns Plinky's own voices into a generative ambient instrument. The chain is a
rolling looper, a granular scatter cloud, a freezing micro-loop, a Dattorro plate reverb
and a bank of tuned resonators, shaped by seven macro sliders: Orbit, Satellite,
Constellate, Tail, Flux, Spectra and Mix.

Two gestures ride on top. Gravity collapses the whole engine into a slow evolving drone;
Event Horizon drains it back to silence for the next phrase. Both live on one bipolar
slider, up and down from centre.

The play surface is tuned in diatonic fourths and follows the selected key and mode, so
every cluster is an open in-key chord and the wash always agrees with what you play.
*/
META
    echo "// GENERATED by amalgamate.sh — single-file Plinky panel. Edit the sources, not this."
    echo "// build ${STAMP_HASH}  generated ${STAMP_TIME}"
    echo "// Ambiotica-on-Plinky. Vendored DSP from ambiotica-plugin, (c) Charles Vestal — MIT (see LICENSE)."
    strip "$HN/amb_config.h"          # build config (LOOPER_I16); per-module flags live in their .c files
    [ -n "$AMB_PROFILE" ] && echo "#define AMB_PROFILE   // per-stage core1 timing (STG printf); set AMB_PROFILE=1 to build"
    strip "$HN/alloc_prelude.h"
    for h in $MODULES; do strip "$DSP/$h.h"; done
    strip "$DSP/rate_util.h"
    strip "$DSP/fast_math.h"
    strip "$HARN/full_chain.h"
    for c in $MODULES; do strip "$DSP/$c.c"; done
    strip "$HN/panel.cpp"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"

# Submission bundle in the plinkysynth/community-panels layout. Built locally every time
# so it never drifts from the sources; submitting is a separate, manual act.
#
#   dist/<key>/<key>.cpp   the panel — filename must match the directory, which IS the key
#   dist/<key>/README.md   shown on the IDE panel cover after someone opens the panel
#   dist/<key>/artwork.png square library thumbnail
#
# The repo allows EXACTLY these three, no subdirectories and no other files, so this
# rebuilds the directory from scratch rather than adding to it. The library listing comes
# from the @-metadata block at the top of the .cpp, not from README.md.
KEY=ambiotica
DIST="$HN/dist/$KEY"
rm -rf "$DIST"
mkdir -p "$DIST"
cp "$OUT"                  "$DIST/$KEY.cpp"
cp "$HN/library_readme.md" "$DIST/README.md"
cp "$HN/artwork.png"       "$DIST/artwork.png"
echo "wrote $DIST/ ($KEY.cpp, README.md, artwork.png)"
