#!/bin/sh
# Amalgamate the Ambiotica port into ONE #include-free .cpp for the Plinky web
# IDE. Order: LOOPER_I16 define -> arena allocator (+ calloc redirect) -> module
# headers -> full_chain -> module implementations -> panel. All #include lines
# are stripped (Plinky auto-injects the standard headers; #include is banned).
set -e
HN="$(cd "$(dirname "$0")" && pwd)"
DSP="$HN/../dsp"
HARN="$HN/../harness"
OUT="$HN/plinky_ambiotica.cpp"

strip() { grep -vE '^[[:space:]]*#[[:space:]]*include' "$1"; }

MODULES="looper granular microloop reverb harmony bloom drift lfo"

{
    echo "// GENERATED by amalgamate.sh — single-file Plinky panel. Edit the sources, not this."
    echo "// Ambiotica-on-Plinky. DSP vendored from schwung-ambiotica (proprietary; private repo)."
    echo "#define LOOPER_I16"
    strip "$HN/alloc_prelude.h"
    for h in $MODULES; do strip "$DSP/$h.h"; done
    strip "$DSP/rate_util.h"
    strip "$HARN/full_chain.h"
    for c in $MODULES; do strip "$DSP/$c.c"; done
    strip "$HN/panel.cpp"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
