#!/bin/sh
# Amalgamate the Ambiotica port into ONE #include-free .cpp for the Plinky web
# IDE. Order: LOOPER_I16 define -> arena allocator (+ calloc redirect) -> module
# headers -> full_chain -> module implementations -> panel. All #include lines
# are stripped (Plinky auto-injects the standard headers; #include is banned).
set -e
HN="$(cd "$(dirname "$0")" && pwd)"
DSP="$HN/../dsp"
HARN="$HN/../harness"

# Build stamp for the generated header: which commit + when it was generated, so
# a downloaded drop-in shows its provenance (CI fills these on every push).
# Falls back gracefully outside a git checkout.
STAMP_HASH="$(git -C "$HN" rev-parse --short HEAD 2>/dev/null || echo nogit)"
git -C "$HN" diff --quiet HEAD 2>/dev/null || STAMP_HASH="${STAMP_HASH}-dirty"
STAMP_TIME="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

# AMB_OUT lets the profiling pass below write to a different file.
OUT="${AMB_OUT:-$HN/plinky_ambiotica.cpp}"

strip() { grep -vE '^[[:space:]]*#[[:space:]]*include' "$1"; }

MODULES="looper granular microloop harmony bloom drift lfo dattorro drums"

# Body first, into a temp file, so it can be comment-stripped before the metadata block is
# prepended. The flash endpoint rejects large uploads ("Request too large") and this project
# comments heavily on purpose - comments were ~45% of a 200 KB file, enough to be refused.
# The sources keep every word; only this artifact is stripped.
BODY="$(mktemp)"
trap 'rm -f "$BODY"' EXIT
{
    strip "$HN/amb_config.h"          # build config (LOOPER_I16); per-module flags live in their .c files
    [ -n "$AMB_PROFILE" ] && echo "#define AMB_PROFILE"
    strip "$HN/alloc_prelude.h"
    for h in $MODULES; do strip "$DSP/$h.h"; done
    strip "$DSP/mipmap.h"             # used by drums.c, so it must precede it
    strip "$DSP/rate_util.h"
    strip "$DSP/fast_math.h"
    strip "$DSP/hann.h"               # AFTER fast_math.h (needs fast_cosf), before its users
    strip "$HARN/full_chain.h"
    for c in $MODULES; do strip "$DSP/$c.c"; done
    strip "$HN/euclid.h"              # after drums.h (needs DRUM_STEPS), before its caller
    strip "$HN/stepcond.h"
    strip "$HN/panel.cpp"
} | python3 "$HN/strip_comments.py" /dev/stdin > "$BODY"

{
    # Panel library metadata. MUST be the first BLOCK comment in the file - that is what
    # the panel library parses (plinkysynth/community-panels), so it is emitted here rather
    # than passing through the comment stripper, which would eat it. @Author and
    # @Documentation are the required fields; @Artwork is banned for community submissions
    # (ship artwork.png beside the .cpp instead).
    cat <<'META'
/*
@Name: Ambiotica
@Author: Charles Vestal
@Documentation: https://github.com/charlesvestal/plinky-ambiotica
@Category: Instruments
@Tags: chords, ambient, drums, granular, reverb, looper, drone
@Discussion: https://github.com/charlesvestal/plinky-ambiotica/issues
@Description: An ambient wash - rolling looper, granular cloud, plate reverb - with an 8-track drum machine under it. Play a few notes and let go. Designed for the Chords faceplate.

Designed for the Chords faceplate: every control sits under the printed word that describes
it, so the overlay documents the panel. It runs on any Plinky 12 - on a different faceplate
you simply lose that correspondence.

Ambiotica turns Plinky's own voices into a generative ambient instrument. The chain is a
rolling looper, a granular scatter cloud, a freezing micro-loop, a Dattorro plate reverb
and a bank of tuned resonators, shaped by seven macro sliders: Orbit, Satellite,
Constellate, Tail, Flux, Spectra and Mix.

Underneath runs an 8-track x0x drum machine, rendered after the chain so it stays dry and
legible under the wash. Its sequencer uses the printed sequencer row: PATTERN generates
Euclidean rhythms, FILL randomises, PROB sets a step's chance, MODULO plays a step only
every Nth time round, and LENGTH gives each track its own loop length for polyrhythms.

Two gestures ride on top. Gravity collapses the whole engine into a slow evolving drone;
Event Horizon drains it back to silence for the next phrase. Both live on one bipolar
slider, up and down from centre.

The play surface is tuned in diatonic fourths and follows the selected key and mode, so
every cluster is an open in-key chord and the wash always agrees with what you play.
*/
META
    echo "// GENERATED by amalgamate.sh - single-file Plinky panel. Edit the sources, not this."
    echo "// build ${STAMP_HASH}  generated ${STAMP_TIME}"
    echo "// Ambiotica-on-Plinky. Vendored DSP from ambiotica-plugin, (c) Charles Vestal - MIT (see LICENSE)."
    echo "// Comments stripped to fit the flash upload limit - the commented sources are in the repo."
    cat "$BODY"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines, $(wc -c < "$OUT" | tr -d ' ') bytes)"

# Amalgamation-order check. This file strips every #include and depends purely on the order
# above, so a use-before-definition compiles fine in the harness and fails only in the IDE.
# Non-fatal: it needs clang, and a missing clang must not stop a build from being produced.
if command -v clang++ >/dev/null 2>&1; then
    python3 "$HN/check_order.py" "$OUT" || echo "amalgamate: ORDER PROBLEM ABOVE - this WILL fail in the IDE" >&2
fi

# Submission bundle in the plinkysynth/community-panels layout. Built locally every time
# so it never drifts from the sources; submitting is a separate, manual act.
#
#   dist/<key>/<key>.cpp   the panel - filename must match the directory, which IS the key
#   dist/<key>/README.md   shown on the IDE panel cover after someone opens the panel
#   dist/<key>/artwork.png square library thumbnail
#
# The repo allows EXACTLY these three, no subdirectories and no other files, so this
# rebuilds the directory from scratch rather than adding to it. The library listing comes
# from the @-metadata block at the top of the .cpp, not from README.md.
# The submission bundle is built only for the normal panel, not the profiling variant.
if [ -n "$AMB_OUT" ]; then exit 0; fi

KEY=ambiotica
DIST="$HN/dist/$KEY"
rm -rf "$DIST"
mkdir -p "$DIST"
cp "$OUT"                  "$DIST/$KEY.cpp"
cp "$HN/library_readme.md" "$DIST/README.md"
cp "$HN/artwork.png"       "$DIST/artwork.png"
echo "wrote $DIST/ ($KEY.cpp, README.md, artwork.png)"

# Profiling variant, built alongside so it can never drift from the real panel. It prints
# per-stage core1 timings (STG loop/gran/mic/rev/harm/mix/push/drum), which is what decides
# where PLINKY_DSP_RAM_FUNC is worth spending the limited SRAM code region on. Deliberately
# NOT in dist/ - that directory allows exactly three files - but published beside the normal
# build so it can be flashed from a URL like any other.
# AMB_OUT guards the recursion: the child sets it, so it builds the body and stops.
if [ -z "$AMB_OUT" ]; then
    AMB_PROFILE=1 AMB_OUT="$HN/plinky_ambiotica_profile.cpp" sh "$0"
fi
